# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settingwindown.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(1050, 480)
        Setting.setMinimumSize(QtCore.QSize(1050, 480))
        Setting.setMaximumSize(QtCore.QSize(1050, 480))
        Setting.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/Icon-Setting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Setting.setWindowIcon(icon)
        self.label_maxvalue_RGB_2 = QtWidgets.QLabel(Setting)
        self.label_maxvalue_RGB_2.setGeometry(QtCore.QRect(680, 20, 61, 21))
        self.label_maxvalue_RGB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maxvalue_RGB_2.setObjectName("label_maxvalue_RGB_2")
        self.doubleSpinBox_Maxvalue_RGB_01 = QtWidgets.QDoubleSpinBox(Setting)
        self.doubleSpinBox_Maxvalue_RGB_01.setEnabled(False)
        self.doubleSpinBox_Maxvalue_RGB_01.setGeometry(QtCore.QRect(740, 20, 91, 22))
        self.doubleSpinBox_Maxvalue_RGB_01.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.doubleSpinBox_Maxvalue_RGB_01.setDecimals(4)
        self.doubleSpinBox_Maxvalue_RGB_01.setMaximum(10000.0)
        self.doubleSpinBox_Maxvalue_RGB_01.setSingleStep(1.0)
        self.doubleSpinBox_Maxvalue_RGB_01.setObjectName("doubleSpinBox_Maxvalue_RGB_01")
        self.doubleSpinBox_Minvalue_RGB_01 = QtWidgets.QDoubleSpinBox(Setting)
        self.doubleSpinBox_Minvalue_RGB_01.setEnabled(False)
        self.doubleSpinBox_Minvalue_RGB_01.setGeometry(QtCore.QRect(911, 20, 91, 22))
        self.doubleSpinBox_Minvalue_RGB_01.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.doubleSpinBox_Minvalue_RGB_01.setDecimals(4)
        self.doubleSpinBox_Minvalue_RGB_01.setMaximum(9999.9999)
        self.doubleSpinBox_Minvalue_RGB_01.setSingleStep(1.0)
        self.doubleSpinBox_Minvalue_RGB_01.setObjectName("doubleSpinBox_Minvalue_RGB_01")
        self.label_minvalue_RGB_01 = QtWidgets.QLabel(Setting)
        self.label_minvalue_RGB_01.setGeometry(QtCore.QRect(850, 20, 61, 21))
        self.label_minvalue_RGB_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_minvalue_RGB_01.setObjectName("label_minvalue_RGB_01")
        self.horizontalSlider_Rcolor = QtWidgets.QSlider(Setting)
        self.horizontalSlider_Rcolor.setEnabled(False)
        self.horizontalSlider_Rcolor.setGeometry(QtCore.QRect(680, 70, 331, 31))
        self.horizontalSlider_Rcolor.setMaximum(255)
        self.horizontalSlider_Rcolor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Rcolor.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_Rcolor.setTickInterval(20)
        self.horizontalSlider_Rcolor.setObjectName("horizontalSlider_Rcolor")
        self.label_value_sliderchangeR = QtWidgets.QLabel(Setting)
        self.label_value_sliderchangeR.setGeometry(QtCore.QRect(1016, 70, 31, 21))
        self.label_value_sliderchangeR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_sliderchangeR.setObjectName("label_value_sliderchangeR")
        self.line = QtWidgets.QFrame(Setting)
        self.line.setGeometry(QtCore.QRect(640, 240, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_testSample_Area = QtWidgets.QPushButton(Setting)
        self.pushButton_testSample_Area.setGeometry(QtCore.QRect(940, 290, 81, 31))
        self.pushButton_testSample_Area.setObjectName("pushButton_testSample_Area")
        self.pushButton_Saveallparameter = QtWidgets.QPushButton(Setting)
        self.pushButton_Saveallparameter.setGeometry(QtCore.QRect(660, 350, 81, 31))
        self.pushButton_Saveallparameter.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Saveallparameter.setFlat(False)
        self.pushButton_Saveallparameter.setObjectName("pushButton_Saveallparameter")
        self.label_Result_test = QtWidgets.QLabel(Setting)
        self.label_Result_test.setGeometry(QtCore.QRect(640, 390, 411, 91))
        self.label_Result_test.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Serif\";")
        self.label_Result_test.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result_test.setObjectName("label_Result_test")
        self.pushButton_DrawRect = QtWidgets.QPushButton(Setting)
        self.pushButton_DrawRect.setGeometry(QtCore.QRect(660, 290, 81, 31))
        self.pushButton_DrawRect.setObjectName("pushButton_DrawRect")
        self.pushButton_RemoveRect = QtWidgets.QPushButton(Setting)
        self.pushButton_RemoveRect.setGeometry(QtCore.QRect(810, 290, 81, 31))
        self.pushButton_RemoveRect.setObjectName("pushButton_RemoveRect")
        self.label_ImageSetting = QtWidgets.QLabel(Setting)
        self.label_ImageSetting.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.label_ImageSetting.setObjectName("label_ImageSetting")
        self.line_4 = QtWidgets.QFrame(Setting)
        self.line_4.setGeometry(QtCore.QRect(630, 0, 20, 571))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_OpenImage = QtWidgets.QPushButton(Setting)
        self.pushButton_OpenImage.setGeometry(QtCore.QRect(810, 350, 81, 31))
        self.pushButton_OpenImage.setObjectName("pushButton_OpenImage")
        self.label_value_sliderchangeG = QtWidgets.QLabel(Setting)
        self.label_value_sliderchangeG.setGeometry(QtCore.QRect(1016, 130, 31, 21))
        self.label_value_sliderchangeG.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_sliderchangeG.setObjectName("label_value_sliderchangeG")
        self.horizontalSlider_Gcolor = QtWidgets.QSlider(Setting)
        self.horizontalSlider_Gcolor.setEnabled(False)
        self.horizontalSlider_Gcolor.setGeometry(QtCore.QRect(680, 130, 331, 31))
        self.horizontalSlider_Gcolor.setMaximum(255)
        self.horizontalSlider_Gcolor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Gcolor.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_Gcolor.setTickInterval(20)
        self.horizontalSlider_Gcolor.setObjectName("horizontalSlider_Gcolor")
        self.label_value_sliderchangeB = QtWidgets.QLabel(Setting)
        self.label_value_sliderchangeB.setGeometry(QtCore.QRect(1016, 190, 31, 21))
        self.label_value_sliderchangeB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value_sliderchangeB.setObjectName("label_value_sliderchangeB")
        self.horizontalSlider_Bcolor = QtWidgets.QSlider(Setting)
        self.horizontalSlider_Bcolor.setEnabled(False)
        self.horizontalSlider_Bcolor.setGeometry(QtCore.QRect(680, 190, 331, 31))
        self.horizontalSlider_Bcolor.setMaximum(255)
        self.horizontalSlider_Bcolor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Bcolor.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_Bcolor.setTickInterval(20)
        self.horizontalSlider_Bcolor.setObjectName("horizontalSlider_Bcolor")
        self.label_R = QtWidgets.QLabel(Setting)
        self.label_R.setGeometry(QtCore.QRect(640, 70, 41, 21))
        self.label_R.setAlignment(QtCore.Qt.AlignCenter)
        self.label_R.setObjectName("label_R")
        self.label_G = QtWidgets.QLabel(Setting)
        self.label_G.setGeometry(QtCore.QRect(640, 130, 41, 21))
        self.label_G.setAlignment(QtCore.Qt.AlignCenter)
        self.label_G.setObjectName("label_G")
        self.label_B = QtWidgets.QLabel(Setting)
        self.label_B.setGeometry(QtCore.QRect(640, 190, 41, 21))
        self.label_B.setAlignment(QtCore.Qt.AlignCenter)
        self.label_B.setObjectName("label_B")
        self.pushButton_SaveImage = QtWidgets.QPushButton(Setting)
        self.pushButton_SaveImage.setGeometry(QtCore.QRect(940, 350, 81, 31))
        self.pushButton_SaveImage.setObjectName("pushButton_SaveImage")
        self.line_4.raise_()
        self.label_maxvalue_RGB_2.raise_()
        self.doubleSpinBox_Maxvalue_RGB_01.raise_()
        self.doubleSpinBox_Minvalue_RGB_01.raise_()
        self.label_minvalue_RGB_01.raise_()
        self.horizontalSlider_Rcolor.raise_()
        self.label_value_sliderchangeR.raise_()
        self.line.raise_()
        self.pushButton_testSample_Area.raise_()
        self.pushButton_Saveallparameter.raise_()
        self.label_Result_test.raise_()
        self.pushButton_DrawRect.raise_()
        self.pushButton_RemoveRect.raise_()
        self.label_ImageSetting.raise_()
        self.pushButton_OpenImage.raise_()
        self.label_value_sliderchangeG.raise_()
        self.horizontalSlider_Gcolor.raise_()
        self.label_value_sliderchangeB.raise_()
        self.horizontalSlider_Bcolor.raise_()
        self.label_R.raise_()
        self.label_G.raise_()
        self.label_B.raise_()
        self.pushButton_SaveImage.raise_()

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "Setting"))
        self.label_maxvalue_RGB_2.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">Max</span></p></body></html>"))
        self.label_minvalue_RGB_01.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;color:red;\">Min </span></p></body></html>"))
        self.label_value_sliderchangeR.setText(_translate("Setting", "0"))
        self.pushButton_testSample_Area.setText(_translate("Setting", "Test"))
        self.pushButton_Saveallparameter.setText(_translate("Setting", "Save"))
        self.label_Result_test.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">No Results</span></p></body></html>"))
        self.pushButton_DrawRect.setText(_translate("Setting", "Draw Rect"))
        self.pushButton_RemoveRect.setText(_translate("Setting", "Remove Rect"))
        self.label_ImageSetting.setText(_translate("Setting", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_OpenImage.setText(_translate("Setting", "Open Image"))
        self.label_value_sliderchangeG.setText(_translate("Setting", "0"))
        self.label_value_sliderchangeB.setText(_translate("Setting", "0"))
        self.label_R.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">R</span></p></body></html>"))
        self.label_G.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">G</span></p></body></html>"))
        self.label_B.setText(_translate("Setting", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#ff0000;\">B</span></p></body></html>"))
        self.pushButton_SaveImage.setText(_translate("Setting", "Save Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setting = QtWidgets.QWidget()
    ui = Ui_Setting()
    ui.setupUi(Setting)
    Setting.show()
    sys.exit(app.exec_())

